#!/usr/bin/env bash

# shellcheck disable=SC2034
PF_COLOR_PRIMARY="$PF_ANSI_GREEN"
PF_COLOR_SECONDARY="$PF_ANSI_GREEN"
PF_COLOR_SUCCESS="$PF_ANSI_GREEN"
PF_COLOR_WARNING="$PF_ANSI_GREEN"
PF_COLOR_ERROR="$PF_ANSI_GREEN"
PF_COLOR_MUTED="$PF_ANSI_BRIGHT_BLACK"
PF_COLOR_RESET="$PF_ANSI_RESET"
